excel_info: 
  excel_path: 'data\abril.xlsm'
  sheet_name: 'Abril'
  fila_inicio: 5
  fecha_consulta: '2025-04-05'
  turno_consulta: 'M'


paths_historic:
  file_hosp: 'data\Ingresados.xlsx' 
  file_historic: 'data\hcoIngresos.xlsx' 