excel_info: 
  excel_path: 'data\mayo.xlsm'
  #sheet_name: 'Mayo'
  fila_inicio: 5
  #fecha_consulta: '2025-05-03'
  #turno_consulta: 'M'


paths_historic:
  file_hosp: 'data\Ingresados.xlsx' 
  file_historic: 'data\hcoIngresos.xlsx' 